//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Challenge()
        {
            this.Tbl_ApprovalStatus = new HashSet<Tbl_ApprovalStatus>();
            this.Tbl_Example = new HashSet<Tbl_Example>();
        }
    
        public int Qid { get; set; }
        public Nullable<int> QpersonOwner { get; set; }
        public string QName { get; set; }
        public string QDescription { get; set; }
        public Nullable<int> QLevel { get; set; }
        public Nullable<byte> QCId { get; set; }
        public Nullable<byte> QStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ApprovalStatus> Tbl_ApprovalStatus { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Level Tbl_Level { get; set; }
        public virtual Tbl_RealPerson Tbl_RealPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Example> Tbl_Example { get; set; }
    }
}
