//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Example
    {
        public int EXId { get; set; }
        public string EXName { get; set; }
        public string EXInputModel { get; set; }
        public string EXOutputModel { get; set; }
        public Nullable<int> EXQId { get; set; }
    
        public virtual Tbl_Challenge Tbl_Challenge { get; set; }
    }
}
