//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PointIncDec
    {
        public int Pid { get; set; }
        public Nullable<int> PUserid { get; set; }
        public Nullable<int> PQid { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<int> PIncDec { get; set; }
    
        public virtual Tbl_Challenge Tbl_Challenge { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
