//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RealPesronPoint
    {
        public int id { get; set; }
        public Nullable<int> PUserId { get; set; }
        public Nullable<int> PPoint { get; set; }
        public Nullable<int> RP_id { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
