//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Level()
        {
            this.Tbl_Challenge = new HashSet<Tbl_Challenge>();
        }
    
        public int LId { get; set; }
        public string LName { get; set; }
        public string LDescription { get; set; }
        public Nullable<int> LOrder { get; set; }
        public Nullable<int> LPointsRequired { get; set; }
        public Nullable<int> LPointReceived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Challenge> Tbl_Challenge { get; set; }
    }
}
