//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    using Models;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_RealPerson = new HashSet<Tbl_RealPerson>();
        }
    
        public int Uid { get; set; }
        public string UuserName { get; set; }
        public string UHashPass { get; set; }
        public Nullable<bool> UActiveStatus { get; set; }
        public Nullable<byte> Role { get; set; }
        

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RealPerson> Tbl_RealPerson { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }

        public EnumRolePage getRole()
        {
            return (EnumRolePage) this.Role;
        }
    }
}
