//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ChallengeApprovalStatus
    {
        public int Qid { get; set; }
        public Nullable<int> QpersonOwner { get; set; }
        public string QName { get; set; }
        public string QDescription { get; set; }
        public Nullable<int> QLevel { get; set; }
        public Nullable<byte> QCId { get; set; }
        public Nullable<byte> QStatus { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<int> SQId { get; set; }
        public Nullable<int> SQPid { get; set; }
        public Nullable<byte> SQStatus { get; set; }
        public Nullable<System.DateTime> SQDate { get; set; }
        public string SQSHDate { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalSHDate { get; set; }
        public Nullable<int> ApprovalPID { get; set; }
        public Nullable<int> SAnswerLanguage { get; set; }
        public string SFileAddress { get; set; }
    }
}
