//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCodeChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Challenge
    {
        public int Qid { get; set; }
        public Nullable<int> QpersonOwner { get; set; }
        public string QName { get; set; }
        public string QDescription { get; set; }
        public Nullable<int> QLevel { get; set; }
        public Nullable<byte> QCId { get; set; }
        public Nullable<byte> QStatus { get; set; }
        public Nullable<int> POwnerUserId { get; set; }
        public string POwnerName { get; set; }
    }
}
